# Pandas

## Tasks Today:
0) <b>From Yesterday...</b>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Numpy where <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) Working with CSV's <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Numpy Exercise <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Numpy Random Sampling <br>

1) <b>Pandas</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Importing <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) Tabular Data Structures <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - from_dict() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - read_csv() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) <b>In-Class Exercise #1</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Accessing Data <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Indexing <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - df.loc <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - keys() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Slicing a DataFrame <br>
 &nbsp;&nbsp;&nbsp;&nbsp; e) Built-In Methods <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - head() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - tail() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - describe() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - sort_values() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - .columns <br>
 &nbsp;&nbsp;&nbsp;&nbsp; f) <b>In-Class Exercise #2</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; g) Filtration <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Conditionals <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Subsetting <br>
 &nbsp;&nbsp;&nbsp;&nbsp; h) Column Transformations <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Generating a New Column w/Data <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - User Defined Function <br>
 &nbsp;&nbsp;&nbsp;&nbsp; i) Aggregations <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - groupby() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Type of groupby() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - mean() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - groupby() w/Multiple Columns <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - drop_duplicates() <br>

#### np.where() <br>
<p>If statement within NDArrays that allows you to run conditionals on the entire array</p>

In [4]:
some_arr = np.arange(2,10)
print(some_arr)

print(np.where(some_arr < 6))
print(some_arr[np.where(some_arr < 6)])

# Transform Data based on a boolean mask == True
some_arr[some_arr < 6] = 17
print(some_arr)


[2 3 4 5 6 7 8 9]
(array([0, 1, 2, 3]),)
[2 3 4 5]
[17 17 17 17  6  7  8  9]


## Working With CSV's

#### Imports

In [5]:
import csv
import numpy as np
from datetime import datetime

#### Loading a CSV's Data 

In [6]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

# i = integer, f = float, |s25 = string with 25 characters, bool = boolean
DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

# instead of loading csv normally, let's load it into a numpy array to calculate results on
def load_data(filename, d = ','):
    data = np.genfromtxt(filename, delimiter = d, skip_header =1,
                        usecols = np.arange(0,24), invalid_raise = False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bos2017 = load_data('../files/redsox_2017_hitting.txt')

names = bos2017['Name']
names

# Find the Total Number of Hits for bostons 2017 Team
total_hits = sum(bos2017['H'])
print(f'Boston 2017 Team had a total of {total_hits} hits!')

# Find the toatl number of HR's for 2017 Team
total_hr = sum(bos2017['HR'])
total_hr
print(f'Boston 2017 Team had a total of {total_hr} home runs!')

Boston 2017 Team had a total of 1459 hits!
Boston 2017 Team had a total of 168 home runs!


#### Summing the top 5 hitters for HR's

In [7]:
# find the top 5 hr hitters
# Step 1: Get all HR data into a variable
# Step 2: Get all Player Names
# Step 3: Create new list for new_names (empty to start)
# Step 4: Decode the player names into regular strings
# Step 5: Grab all data and place inside of a zipped list
# Step 6: Sort values based on HR data

# Step 1
all_hr = bos2017['HR']
# print(all_hr)
# Step 2
all_names = bos2017['Name']

# Step 3
new_names = []


# Step 4
for i in range(len(all_names)):
    new_names.append(all_names[i].decode('utf-8'))

# print(new_names)

# Step 5
zipped_values = list(zip(new_names, all_hr))
# print(zipped_values)

# Step 6
sorted_hr = sorted(zipped_values, key = lambda x: x[1], reverse = True)
print(sorted_hr[0:5])





[('Mookie Betts', 24), ('Hanley Ramirez', 23), ('Mitch Moreland', 22), ('Andrew Benintendi', 20), ('Jackie Bradley Jr.', 17)]


## Numpy Random Sampling

In [8]:
import numpy as np

# A single call generates a single random number
print('Here is a random number: %s' % np.random.uniform())
print(f'Here is a random number: {np.random.uniform()}')

# You can also pass some bounds
print('Here is a random number between 0 and 1 Million: %s' % np.random.uniform(0, 1e6))

# You can also generate a bunch of random numbers all at once
print('Here are 3 random numbers between 0 and 1 Million: %s' % np.random.uniform(0, 1e6, 3))

# Even matrices and tensors with weird shapes
print('Here is a 3x3 matrix of random numbers between 0 and 1 Million: \n %s' % np.random.uniform(0, 1e6, (3, 3)))

# instead of float values, generating random integers
print('Using Random Integer: %s' % np.random.randint(0, 1000))

Here is a random number: 0.4814964836980943
Here is a random number: 0.924195239713532
Here is a random number between 0 and 1 Million: 293790.2085783007
Here are 3 random numbers between 0 and 1 Million: [ 85994.79513886 141796.59933217 227892.12754567]
Here is a 3x3 matrix of random numbers between 0 and 1 Million: 
 [[368769.49726949 623586.34060035  34731.71026819]
 [561991.27495959 415032.73633787 749735.75036236]
 [565274.70033005  85876.62516702 755164.19979378]]
Using Random Integer: 954


## Pandas <br>

<p>Pandas is a flexible data analysis library built on top of NumPy that is excellent for working with tabular data. It is currently the de-facto standard for Python-based data analysis, and fluency in Pandas will do wonders for your productivity and frankly your resume. It is one of the fastest ways of getting from zero to answer in existence. </p>

<ul>
    <li>Pandas is a Python module, written in C. The Pandas module is a high performance, highly efficient, and high level data analysis library. It allows us to work with large sets of data called dataframes.</li>
    <li>Series is a one-dimensional labeled array capable of holding data of any type (integer, string, float, python objects, etc.)</li>
    <li>Dataframe = Spreadsheet (has column headers, index, etc.)</li>
</ul>

### Importing

In [9]:
!pip install pandas

In [10]:
import pandas as pd

# always use pd, standard for data science

### Tabular data structures <br>
<p>The central object of study in Pandas is the DataFrame, which is a tabular data structure with rows and columns like an excel spreadsheet. The first point of discussion is the creation of dataframes both from native Python dictionaries, and text files through the Pandas I/O system.</p>

In [11]:
names = ['Alice',
         'Bob',
         'James',
         'Beth', 
         'John', 
         'Sally',
         'Richard', 
         'Lauren',
         'Brandon', 
         'Sabrina']

ages = np.random.randint(18,35,len(names))

print(names)
print(ages)
my_people = {
    'names': names,
    'ages': ages
}

my_people


['Alice', 'Bob', 'James', 'Beth', 'John', 'Sally', 'Richard', 'Lauren', 'Brandon', 'Sabrina']
[25 29 32 22 25 28 18 27 21 30]


{'names': ['Alice',
  'Bob',
  'James',
  'Beth',
  'John',
  'Sally',
  'Richard',
  'Lauren',
  'Brandon',
  'Sabrina'],
 'ages': array([25, 29, 32, 22, 25, 28, 18, 27, 21, 30])}

##### from_dict()

<p>Let's convert our not-so-useful-for-analysis dict into a Pandas dataframe. We can use the from_dict function to do this easily using Pandas:</p>

In [12]:
data = pd.DataFrame.from_dict(my_people)

data

names  ages
0    Alice    25
1      Bob    29
2    James    32
3     Beth    22
4     John    25
5    Sally    28
6  Richard    18
7   Lauren    27
8  Brandon    21
9  Sabrina    30

##### read_csv()

In [186]:
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)
marathon = pd.read_csv('../files/boston_marathon2017_edited.csv', sep = ',')

0        12/30/1899 12:04:57 AM
1        12/30/1899 12:04:58 AM
2        12/30/1899 12:04:59 AM
3        12/30/1899 12:05:03 AM
4        12/30/1899 12:05:04 AM
                  ...          
26405    12/30/1899 12:16:24 AM
26406    12/30/1899 12:16:40 AM
26407    12/30/1899 12:16:47 AM
26408    12/30/1899 12:16:49 AM
26409    12/30/1899 12:18:15 AM
Name: Pace, Length: 26410, dtype: object

### In-Class Exercise #1 - Read in Boston Red Sox Hitting Data <br>
<p>Use the pandas read_csv() method to read in the statistics from the two files yesterday.</p>

In [14]:
bb2017 = pd.read_csv('../files/redsox_2017_hitting.txt')
bb2018 = pd.read_csv('../files/redsox_2018_hitting.txt')

bb2017

Rk Pos                Name  Age    G   PA   AB    R    H  2B  ...    OBP  \
0    1   C   Christian Vazquez   26   99  345  324   43   94  18  ...  0.330   
1    2  1B      Mitch Moreland   31  149  576  508   73  125  34  ...  0.326   
2    3  2B      Dustin Pedroia   33  105  463  406   46  119  19  ...  0.369   
3    4  SS     Xander Bogaerts   24  148  635  571   94  156  32  ...  0.343   
4    5  3B       Rafael Devers   20   58  240  222   34   63  14  ...  0.338   
5    6  LF   Andrew Benintendi   22  151  658  573   84  155  26  ...  0.352   
6    7  CF  Jackie Bradley Jr.   27  133  541  482   58  118  19  ...  0.323   
7    8  RF        Mookie Betts   24  153  712  628  101  166  46  ...  0.344   
8    9  DH      Hanley Ramirez   33  133  553  496   58  120  24  ...  0.320   
9   10   C          Sandy Leon   28   85  301  271   32   61  14  ...  0.290   
10  11  UT         Chris Young   33   90  276  243   30   57  12  ...  0.322   
11  12  3B       Deven Marrero   26   71  188  171   32   36   9  ...  0.259   
12  13  2B       Eduardo Nunez   30   38  173  165   23   53  12  ...  0.353   
13  14  2B          Brock Holt   29   64  164  140   20   28   6  ...  0.305   
14  15  IF       Josh Rutledge   28   37  118  107   10   24   2  ...  0.297   
15  16  3B      Pablo Sandoval   30   32  108   99   10   21   2  ...  0.269   
16  17  UT          Sam Travis   23   33   83   76   13   20   6  ...  0.325   
17  18  UT         Tzu-Wei Lin   23   25   66   56    7   15   0  ...  0.369   
18  19  IF     Marco Hernandez   24   21   60   58    7   16   3  ...  0.300   
19  20  UT         Rajai Davis   36   17   38   36    7    9   2  ...  0.289   
20  21  UT        Steve Selsky   27    8    9    9    0    1   1  ...  0.111   
21  22  UT       Blake Swihart   25    6    7    5    1    1   0  ...  0.429   
22  23  2B      Chase d'Arnaud   30    2    1    1    2    1   0  ...  1.000   

      SLG    OPS  OPS+   TB  GDP  HBP  SH  SF  IBB  
0   0.404  0.735    91  131   14    3   0   1    0  
1   0.443  0.769    99  225   14    6   0   5    6  
2   0.392  0.760   100  159   11    2   2   4    4  
3   0.403  0.746    95  230   17    6   0   2    6  
4   0.482  0.819   111  107    5    0   0   0    3  
5   0.424  0.776   102  243   16    6   1   8    7  
6   0.402  0.726    89  194    8    9   0   2    4  
7   0.459  0.803   108  288    9    2   0   5    9  
8   0.429  0.750    94  213   15    6   0   0    8  
9   0.354  0.644    68   96    5    1   1   3    1  
10  0.387  0.709    85   94    4    2   0   1    0  
11  0.333  0.593    54   57    8    0   3   2    0  
12  0.539  0.892   128   89    3    2   0   0    0  
13  0.243  0.548    47   34    3    3   0   2    0  
14  0.262  0.558    49   28    1    2   0   0    0  
15  0.354  0.622    61   35    4    0   0   1    0  
16  0.342  0.667    75   26    2    1   0   0    0  
17  0.339  0.709    88   19    0    0   1   0    0  
18  0.328  0.628    65   19    0    1   0   0    0  
19  0.306  0.595    56   11    2    1   0   0    0  
20  0.222  0.333   -16    2    0    0   0   0    0  
21  0.200  0.629    74    1    0    0   0   0    0  
22  1.000  2.000   428    1    0    0   0   0    0  

[23 rows x 28 columns]

### Accessing Data <br>

##### Indexing

<p>You can directly select a column of a dataframe just like you would a dict. The result is a Pandas 'Series' object.</p>

In [18]:
print(data)
data_ages = data['ages']

print(data_ages)

# print out the type of the variable data
# Series
print(type(data_ages))

# DataFrame
print(type(data))

# DataSeries Index - starting at 0 
print(data_ages[4])

# key first, row index second
print(data['ages'][4])

     names  ages
0    Alice    25
1      Bob    29
2    James    32
3     Beth    22
4     John    25
5    Sally    28
6  Richard    18
7   Lauren    27
8  Brandon    21
9  Sabrina    30
0    25
1    29
2    32
3    22
4    25
5    28
6    18
7    27
8    21
9    30
Name: ages, dtype: int64
<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
25
25


##### df.loc

<p>Along the horizontal dimension, rows of Pandas DataFrames are Row objects. You will notice there is a third column present in the DataFrame - this is the $\textit{index}$. It is automatically generated as a row number, but can be reassigned to a column of your choice using the DataFrame.set_index(colname) method. We can use it to access particular Pandas $\textit{rows}$, which are also Series objects:</p>

In [67]:
# Grab the first row of data -- by the index of the row
my_row = data.loc[1]
my_row

# Getting Multiple values from a df.loc
multiple_rows = data.loc[[0,2,9]]['ages']
multiple_rows


# Using df.loc and producing a Dataframe at the end
first_5_df = data.loc[[0,1,2,3,4]]
first_5_df

# Reset our my_people dataframe index
new_index = first_5_df.set_index('ages')
print(new_index)

new_index.loc[25]
# print(reset_index.loc['James'])
# print(data.loc[2])

      names
ages       
25    Alice
29      Bob
32    James
22     Beth
25     John


names
ages       
25    Alice
25     John

##### keys()

In [78]:
# Access all of the keys/columns of the dataframe
# Dataframe.keys()

print(type(bb2017.keys()))
print(type(bb2017.keys().tolist()))
print(bb2017.keys().tolist())
# for label in bb2017.keys().tolist():
#     print(f'{label}: {bb2017.loc[0][label]}')

<class 'pandas.core.indexes.base.Index'>
<class 'list'>
['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']


##### Slicing a DataFrame

In [85]:
# printing all data for context
bb2017[3:7]

Rk Pos                Name  Age    G   PA   AB   R    H  2B  ...    OBP  \
3   4  SS     Xander Bogaerts   24  148  635  571  94  156  32  ...  0.343   
4   5  3B       Rafael Devers   20   58  240  222  34   63  14  ...  0.338   
5   6  LF   Andrew Benintendi   22  151  658  573  84  155  26  ...  0.352   
6   7  CF  Jackie Bradley Jr.   27  133  541  482  58  118  19  ...  0.323   

     SLG    OPS  OPS+   TB  GDP  HBP  SH  SF  IBB  
3  0.403  0.746    95  230   17    6   0   2    6  
4  0.482  0.819   111  107    5    0   0   0    3  
5  0.424  0.776   102  243   16    6   1   8    7  
6  0.402  0.726    89  194    8    9   0   2    4  

[4 rows x 28 columns]

### Built-In Methods <br>

<p>These are methods that are frequently used when using Pandas to make your life easier. It is possible to spend a whole week simply exploring the built-in functions supported by DataFrames in Pandas. Here however, we will simply highlight a few ones that might be useful, to give you an idea of what's possible out of the box with Pandas:</p>

##### head()

In [96]:
# DataFrame.head()  -- Accepts integer parameter(gives access to more rows) -- defaults to 5
bb2017.head(7)

Rk Pos                Name  Age    G   PA   AB   R    H  2B  ...    OBP  \
0   1   C   Christian Vazquez   26   99  345  324  43   94  18  ...  0.330   
1   2  1B      Mitch Moreland   31  149  576  508  73  125  34  ...  0.326   
2   3  2B      Dustin Pedroia   33  105  463  406  46  119  19  ...  0.369   
3   4  SS     Xander Bogaerts   24  148  635  571  94  156  32  ...  0.343   
4   5  3B       Rafael Devers   20   58  240  222  34   63  14  ...  0.338   
5   6  LF   Andrew Benintendi   22  151  658  573  84  155  26  ...  0.352   
6   7  CF  Jackie Bradley Jr.   27  133  541  482  58  118  19  ...  0.323   

     SLG    OPS  OPS+   TB  GDP  HBP  SH  SF  IBB  
0  0.404  0.735    91  131   14    3   0   1    0  
1  0.443  0.769    99  225   14    6   0   5    6  
2  0.392  0.760   100  159   11    2   2   4    4  
3  0.403  0.746    95  230   17    6   0   2    6  
4  0.482  0.819   111  107    5    0   0   0    3  
5  0.424  0.776   102  243   16    6   1   8    7  
6  0.402  0.726    89  194    8    9   0   2    4  

[7 rows x 28 columns]

##### tail()

In [99]:
# DataFrame.tail()  -- Accepts integer parameter(gives access to more rows) -- also defaults to 5
bb2017.tail(9)

Rk Pos             Name  Age   G   PA   AB   R   H  2B  ...    OBP    SLG  \
14  15  IF    Josh Rutledge   28  37  118  107  10  24   2  ...  0.297  0.262   
15  16  3B   Pablo Sandoval   30  32  108   99  10  21   2  ...  0.269  0.354   
16  17  UT       Sam Travis   23  33   83   76  13  20   6  ...  0.325  0.342   
17  18  UT      Tzu-Wei Lin   23  25   66   56   7  15   0  ...  0.369  0.339   
18  19  IF  Marco Hernandez   24  21   60   58   7  16   3  ...  0.300  0.328   
19  20  UT      Rajai Davis   36  17   38   36   7   9   2  ...  0.289  0.306   
20  21  UT     Steve Selsky   27   8    9    9   0   1   1  ...  0.111  0.222   
21  22  UT    Blake Swihart   25   6    7    5   1   1   0  ...  0.429  0.200   
22  23  2B   Chase d'Arnaud   30   2    1    1   2   1   0  ...  1.000  1.000   

      OPS  OPS+  TB  GDP  HBP  SH  SF  IBB  
14  0.558    49  28    1    2   0   0    0  
15  0.622    61  35    4    0   0   1    0  
16  0.667    75  26    2    1   0   0    0  
17  0.709    88  19    0    0   1   0    0  
18  0.628    65  19    0    1   0   0    0  
19  0.595    56  11    2    1   0   0    0  
20  0.333   -16   2    0    0   0   0    0  
21  0.629    74   1    0    0   0   0    0  
22  2.000   428   1    0    0   0   0    0  

[9 rows x 28 columns]

##### shape

In [102]:
# The dataframe has a shape property, just like a NumPy matrix. 
# print(df.shape) -- DataFrame.shape -- No Parameter

bb2017.shape


(23, 28)

##### describe() <br>
<p>Probably one of the most important methods to understand...</p>

In [127]:
# Collect summary statistics in one line
# DataFrame.describe() -- Accepts parameters (include, exclude)
bb2017.describe()
# bb2017.describe(include='all')

Rk        Age           G          PA          AB           R  \
count  23.00000  23.000000   23.000000   23.000000   23.000000   23.000000   
mean   12.00000  27.478261   72.086957  274.565217  245.521739   34.130435   
std     6.78233   4.110624   52.747178  236.592059  209.032157   30.804817   
min     1.00000  20.000000    2.000000    1.000000    1.000000    0.000000   
25%     6.50000  24.000000   28.500000   74.500000   67.000000    8.500000   
50%    12.00000  27.000000   64.000000  188.000000  171.000000   30.000000   
75%    17.50000  30.000000  119.000000  502.000000  444.000000   52.000000   
max    23.00000  36.000000  153.000000  712.000000  628.000000  101.000000   

                H         2B         3B         HR  ...        OBP        SLG  \
count   23.000000  23.000000  23.000000  23.000000  ...  23.000000  23.000000   
mean    63.434783  13.086957   0.826087   7.304348  ...   0.346217   0.393348   
std     55.645653  12.630817   1.466355   8.309003  ...   0.153742   0.156269   
min      1.000000   0.000000   0.000000   0.000000  ...   0.111000   0.200000   
25%     18.000000   2.000000   0.000000   0.000000  ...   0.298500   0.330500   
50%     53.000000  12.000000   0.000000   5.000000  ...   0.325000   0.387000   
75%    118.500000  19.000000   1.500000  10.000000  ...   0.348000   0.426500   
max    166.000000  46.000000   6.000000  24.000000  ...   1.000000   1.000000   

             OPS        OPS+          TB        GDP        HBP         SH  \
count  23.000000   23.000000   23.000000  23.000000  23.000000  23.000000   
mean    0.739609   93.521739  100.086957   6.130435   2.304348   0.347826   
std     0.298278   78.686299   91.930267   5.786382   2.566122   0.775107   
min     0.333000  -16.000000    1.000000   0.000000   0.000000   0.000000   
25%     0.625000   63.000000   22.500000   1.500000   0.000000   0.000000   
50%     0.709000   88.000000   89.000000   4.000000   2.000000   0.000000   
75%     0.764500   99.500000  176.500000  10.000000   3.000000   0.000000   
max     2.000000  428.000000  288.000000  17.000000   9.000000   3.000000   

              SF        IBB  
count  23.000000  23.000000  
mean    1.565217   2.086957  
std     2.149547   3.073539  
min     0.000000   0.000000  
25%     0.000000   0.000000  
50%     1.000000   0.000000  
75%     2.000000   4.000000  
max     8.000000   9.000000  

[8 rows x 26 columns]

##### sort_values()

In [138]:
# Sort based on many labels, with left-to-right priority
# DataFrame.sort_values('key')
print(data)
sorted_data = data.sort_values('ages', kind = 'mergesort')
print(sorted_data)

sorted_data.reset_index(drop=True)



     names  ages
0    Alice    25
1      Bob    29
2    James    32
3     Beth    22
4     John    25
5    Sally    28
6  Richard    18
7   Lauren    27
8  Brandon    21
9  Sabrina    30
     names  ages
6  Richard    18
8  Brandon    21
3     Beth    22
0    Alice    25
4     John    25
7   Lauren    27
5    Sally    28
1      Bob    29
9  Sabrina    30
2    James    32


names  ages
0  Richard    18
1  Brandon    21
2     Beth    22
3    Alice    25
4     John    25
5   Lauren    27
6    Sally    28
7      Bob    29
8  Sabrina    30
9    James    32

##### .columns

In [142]:
# will show all cols headers
# DataFrame.columns -- has no parameters

print(bb2017.columns)
print(f'\nThe type of bb2017.columns: {type(bb2017.columns)}')
print('\n')
print(bb2017.keys())
print(f'\nThe type of bb2017.keys(): {type(bb2017.keys())}')

Index(['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR',
       'RBI', 'SB', 'CS', 'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB',
       'GDP', 'HBP', 'SH', 'SF', 'IBB'],
      dtype='object')

The type of bb2017.columns: <class 'pandas.core.indexes.base.Index'>


Index(['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR',
       'RBI', 'SB', 'CS', 'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB',
       'GDP', 'HBP', 'SH', 'SF', 'IBB'],
      dtype='object')

The type of bb2017.keys(): <class 'pandas.core.indexes.base.Index'>


### In-Class Exercise #2 - Describe & Sort Boston Red Sox Hitting Data <br>
<p>Take the data that you read in earlier from the Red Sox csv's and use the describe method to understand the data better. Compare the two years and decide which team is having the better year. Then sort the values based on Batting Average.</p>

In [158]:
avr17 = bb2017['BA'].describe()['mean']
avr18 = bb2018['BA'].describe()['mean']
print(avr17, avr18)

if avr17 > avr18:
    print('2017 was a better year')
else:
    print('18 was better')
    
    
ba17 = bb2017.describe()['BA']['mean']
ba17

0.27843478260869564 0.23795000000000002
2017 was a better year


0.27843478260869564

### Filtration <br>
<p>Let's look at how to filter dataframes for rows that fulfill a specific conditon.</p>

##### Conditionals

In [161]:
# Conditional boolean dataframe
print(data)
data['ages'] >= 25

     names  ages
0    Alice    25
1      Bob    29
2    James    32
3     Beth    22
4     John    25
5    Sally    28
6  Richard    18
7   Lauren    27
8  Brandon    21
9  Sabrina    30


0     True
1     True
2     True
3    False
4     True
5     True
6    False
7     True
8    False
9     True
Name: ages, dtype: bool

##### Subsetting

In [165]:
# exactly like numpy
data[data['ages'] >= 25]

# SELECT *
# FROM data
# WHERE ages >= 25

names  ages
0    Alice    25
1      Bob    29
2    James    32
4     John    25
5    Sally    28
7   Lauren    27
9  Sabrina    30

### Column Transformations <br>
<p>Rarely, if ever, will the columns in the original raw dataframe read from CSV or database table be the ones you actually need for your analysis. You will spend lots of time constantly transforming columns or groups of columns using general computational operations to produce new ones that are functions of the old ones. Pandas has full support for this: Consider the following dataframe containing membership term and renewal number for a group of customers:</p>

In [167]:
# Generate some fake data
customer_id = np.random.randint(1000,1100, 10)
renewal_nbr = np.random.randint(0,10,10)
customer_dict = {1: 0.5, 0: 1}
terms_in_years = [customer_dict[key] for key in np.random.randint(0,2,10)]

random_data = {
    'customer_id': customer_id,
    'renewal_nbr': renewal_nbr,
    'term_in_years': terms_in_years
}

print(random_data)
customers = pd.DataFrame.from_dict(random_data)
customers

{'customer_id': array([1046, 1088, 1064, 1029, 1042, 1086, 1024, 1002, 1041, 1054]), 'renewal_nbr': array([5, 9, 2, 1, 3, 9, 9, 5, 4, 1]), 'term_in_years': [0.5, 1, 1, 0.5, 0.5, 1, 1, 1, 0.5, 1]}


customer_id  renewal_nbr  term_in_years
0         1046            5            0.5
1         1088            9            1.0
2         1064            2            1.0
3         1029            1            0.5
4         1042            3            0.5
5         1086            9            1.0
6         1024            9            1.0
7         1002            5            1.0
8         1041            4            0.5
9         1054            1            1.0

##### Generating a New Column w/Data

In [168]:
# DataFrame['key'] = Some Calculation from our DataFrame Columns
customers['customer_tenure'] = customers['renewal_nbr'] * customers['term_in_years']

customers

customer_id  renewal_nbr  term_in_years  customer_tenure
0         1046            5            0.5              2.5
1         1088            9            1.0              9.0
2         1064            2            1.0              2.0
3         1029            1            0.5              0.5
4         1042            3            0.5              1.5
5         1086            9            1.0              9.0
6         1024            9            1.0              9.0
7         1002            5            1.0              5.0
8         1041            4            0.5              2.0
9         1054            1            1.0              1.0

##### User Defined Function

<p>If what you want to do to a column that can't be represented by simple mathematical operations, you can write your own $\textit{user defined function}$ with the full customizability available in Python and any external Python packages, then map it directly onto a column. Let's add some ages to our customer dataframe, and then classify them into our custom defined grouping scheme:</p>

In [174]:
# Create a new column for ages
customers['ages'] = np.random.randint(18,70,10)
customers

# use .apply to map over dataframe
def make_groups(age):
    if age < 20:
        return 'Teenager'
    elif age < 35:
        return 'Young Adult'
    elif age < 65:
        return 'Adult'
    else:
        return 'Senior'

customers['age_group'] = customers['ages'].apply(make_groups)
customers

customer_id  renewal_nbr  term_in_years  customer_tenure  ages    age_group
0         1046            5            0.5              2.5    32  Young Adult
1         1088            9            1.0              9.0    25  Young Adult
2         1064            2            1.0              2.0    30  Young Adult
3         1029            1            0.5              0.5    18     Teenager
4         1042            3            0.5              1.5    23  Young Adult
5         1086            9            1.0              9.0    58        Adult
6         1024            9            1.0              9.0    47        Adult
7         1002            5            1.0              5.0    49        Adult
8         1041            4            0.5              2.0    68       Senior
9         1054            1            1.0              1.0    47        Adult

<p>As a last example I'll show here how you would use a lambda function to create a UDF that depends on $\textit{more than one}$ column:</p>

<li>UDF = User Defined Function</li>

In [177]:
#Axis for apply can only be 1 or 0 -- 1 being the X axis 0 being the Y axis
def make_loyalty_groups(row):
    age = row['ages'] # cusomters[0]['ages']
    tenure = row['customer_tenure']
    if age < 20:
        age_group = 'Teenager'
    elif age < 35:
        age_group =  'Young Adult'
    elif age < 65:
        age_group = 'Adult'
    else:
        age_group = 'Senior'
        
    if tenure > 2:
        return f'Loyal {age_group}'
    else:
        return f'New {age_group}'
    
customers['loyalty_age_group'] = customers.apply(make_loyalty_groups, axis = 1)
customers

customer_id  renewal_nbr  term_in_years  customer_tenure  ages  \
0         1046            5            0.5              2.5    32   
1         1088            9            1.0              9.0    25   
2         1064            2            1.0              2.0    30   
3         1029            1            0.5              0.5    18   
4         1042            3            0.5              1.5    23   
5         1086            9            1.0              9.0    58   
6         1024            9            1.0              9.0    47   
7         1002            5            1.0              5.0    49   
8         1041            4            0.5              2.0    68   
9         1054            1            1.0              1.0    47   

     age_group  loyalty_age_group  
0  Young Adult  Loyal Young Adult  
1  Young Adult  Loyal Young Adult  
2  Young Adult    New Young Adult  
3     Teenager       New Teenager  
4  Young Adult    New Young Adult  
5        Adult        Loyal Adult  
6        Adult        Loyal Adult  
7        Adult        Loyal Adult  
8       Senior         New Senior  
9        Adult          New Adult

### Homework Exercise #3 - Create Your Own UDF <br>
<p>Using the Boston Red Sox data, create your own UDF which creates a new column called 'All-Star' and puts every player with either a batting average over .280 or an on base percentage of over .360 with a result of 'Yes' in the column and 'No' if not.</p>

In [ ]:
"""
    Name  BA OBP AllStar
    --------------------
    Name .233 .360 Yes
    Name .150 .288 No
"""



### Aggregations <br>
<p>The raw data plus some transformations is generally only half the story. Your objective is to extract actual insights and actionable conclusions from the data, and that means reducing it from potentially billions of rows to some summary statistics via aggregation functions.</p>

##### groupby() <br>
<p>The .groupby() function is in some ways a 'master' aggregation.</p> 

<p>Data tables will usually reserve one column as a primary key - that is, a column for which each row has a unique value. This is to facilitate access to the exact rows of a data table that a user wants to view. The other columns will often have repeated values, such as the age groups in the above examples. We can use these columns to explore the data using the Pandas API:</p>

In [ ]:
# also introducing .count() here, exact same as to how it's used in SQL

# Using the groupby with the column intact as a column/key
# customers.groupby('age_group', as_index = False).count()[['customer_id','age_group']]



##### Type of groupby()

<p>The result is a new dataframe, the columns of which all contain the counts of the grouped field. Notice the type of a grouped dataframe:</p>

In [ ]:
print(type(customers), 'Regular Data Frame')
print(f'\n Type of Group By for Customer.GroupBy: {type(customers.groupby("age_group"))}')

<p>This is because simply grouping data doesn't quite make sense without an aggregation function like count() to pair with. In this case, we're counting occurances of the grouped field, but that's not all we can do. We can take averages, standard deviations, mins, maxes and much more! Let's see how this works a bit more:</p>

##### mean()

In [ ]:
# mean = average


##### groupby() w/Multiple Columns

<p>We end up with the average age of the groups in the last column, the average tenure in the tenure column, and so on and so forth. You can even split the groups more finely by passing a list of columns to group by:</p>

##### drop_duplicates()

<p>Drops all duplicates from the current dataframe</p>

In [ ]:
customers

In [ ]:
# Send customer data into a CSV file
customers_copy.to_csv('../files/customers.csv')

<p>Thus the groupby operation allows you to rapidly make summary observations about the state of your entire dataset at flexible granularity. In one line above, we actually did something very complicated - that's the power of the dataframe. In fact, the process often consists of several iterative groupby operations, each revealing greater insight than the last - if you don't know where to start with a dataset, try a bunch of groupbys!</p>

### Homework Excersise #1 - Find the Total Number of Runs and RBIs for the Red Sox <br>
<p>Get total number of home runs and rbi's</p>

In [ ]:
# step 1: Add a new column with the key 'Team' and all column values should be 'BOS'

# step 2: Group by the 'Team' column and get total home runs and rbi's

# Produce data for both 2017 and 2018 (ie print both seperated by a newline character \n)

"""
TEAM    HR   RBI
----------------
BOS     144  538
"""


## Find the average age of runners in the 2017 Boston Marathon